services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./StudentMangagementAppBackend
      dockerfile: Dockerfile
    container_name: student-backend
    ports:
      - "8082:8082"
    depends_on:
      mysql-db:
        condition: service_healthy

  frontend:
    build:
      context: ./student-management-app
      dockerfile: Dockerfile
    container_name: student-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: